#!/bin/bash
# Interactive setup script for Proxmox Monitor
# Guides user through initial configuration

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Determine config file location
if [ "$1" == "--system" ]; then
    # System installation - save to /opt/proxmox-monitor so app finds it first
    CONFIG_FILE="/opt/proxmox-monitor/config/config.yaml"
    CONFIG_TEMPLATE="/opt/proxmox-monitor/config/config.empty.yaml"
    IS_SYSTEM=true
else
    # Local development
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
    CONFIG_FILE="$PROJECT_ROOT/config/config.yaml"
    CONFIG_TEMPLATE="$PROJECT_ROOT/config/config.empty.yaml"
    IS_SYSTEM=false
fi

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${YELLOW}config.yaml already exists at $CONFIG_FILE${NC}"
    read -p "Do you want to reconfigure? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Configuration skipped"
        exit 0
    fi
fi

# Check if template exists
if [ ! -f "$CONFIG_TEMPLATE" ]; then
    echo -e "${RED}Error: Template file not found at $CONFIG_TEMPLATE${NC}"
    exit 1
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Welcome to Proxmox Monitor Setup Wizard${NC}"
echo -e "${BLUE}║   Interactive Configuration Tool${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Ensure config directory exists
CONFIG_DIR="$(dirname "$CONFIG_FILE")"
if [ ! -d "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
fi

# Copy template
cp "$CONFIG_TEMPLATE" "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

# 1. Telegram Bot Configuration
echo -e "${YELLOW}=== Telegram Bot Configuration ===${NC}"
echo ""
echo "To get your bot token:"
echo "  1. Talk to @BotFather on Telegram"
echo "  2. Create a new bot with /newbot"
echo "  3. Copy the bot token"
echo ""

read -p "Telegram bot token: " BOT_TOKEN

if [ -z "$BOT_TOKEN" ]; then
    echo -e "${RED}Error: Bot token cannot be empty${NC}"
    exit 1
fi

# 2. Access Control
echo ""
echo -e "${YELLOW}=== Access Control Configuration ===${NC}"
echo ""
echo "To get your Telegram user ID:"
echo "  1. Write a message to @GetMyID_bot"
echo "  2. It will show your user ID"
echo ""

read -p "Your Telegram user ID (for bot access): " USER_ID
read -p "Chat ID to send alerts to (same as user ID or group ID): " CHAT_ID

if [ -z "$USER_ID" ] || [ -z "$CHAT_ID" ]; then
    echo -e "${RED}Error: User ID and Chat ID cannot be empty${NC}"
    exit 1
fi

# 3. Alert Thresholds
echo ""
echo -e "${YELLOW}=== Alert Thresholds Configuration ===${NC}"
echo ""
echo "Enter threshold values (percentage, default values shown):"
echo ""

read -p "CPU usage warning threshold (default 80): " CPU_WARN
CPU_WARN=${CPU_WARN:-80}

read -p "CPU usage critical threshold (default 95): " CPU_CRIT
CPU_CRIT=${CPU_CRIT:-95}

read -p "RAM usage warning threshold (default 85): " RAM_WARN
RAM_WARN=${RAM_WARN:-85}

read -p "RAM usage critical threshold (default 95): " RAM_CRIT
RAM_CRIT=${RAM_CRIT:-95}

read -p "Disk usage warning threshold (default 85): " DISK_WARN
DISK_WARN=${DISK_WARN:-85}

read -p "Disk usage critical threshold (default 95): " DISK_CRIT
DISK_CRIT=${DISK_CRIT:-95}

# Update config with YAML structure
cat > "$CONFIG_FILE" << EOF
# Proxmox Monitor - Configuration File
# Generated by setup.sh

telegram:
  # Telegram bot token from @BotFather
  token: "$BOT_TOKEN"
  
  # List of Telegram user IDs allowed to use bot commands
  allowed_user_ids: [$USER_ID]
  
  # Chat ID where notifications will be sent
  chat_id: $CHAT_ID

proxmox:
  # Proxmox node name (use 'pvesh get /nodes' to find)
  node: "pve"
  
  # List of required CT IDs that should be monitored for status
  required_cts: []
  
  # List of required VM IDs that should be monitored for status
  required_vms: []

# Alert thresholds (percentage values)
thresholds:
  cpu:
    warning: $CPU_WARN      # Alert if CPU > $CPU_WARN%
    critical: $CPU_CRIT     # Critical alert if CPU > $CPU_CRIT%
  
  ram:
    warning: $RAM_WARN      # Alert if RAM usage > $RAM_WARN%
    critical: $RAM_CRIT     # Critical alert if RAM usage > $RAM_CRIT%
  
  swap:
    warning: 50      # Alert if swap used > 50%
    critical: 80     # Critical alert if swap used > 80%
  
  disk:
    warning: $DISK_WARN      # Alert if disk usage > $DISK_WARN%
    critical: $DISK_CRIT     # Critical alert if disk usage > $DISK_CRIT%

# Scheduler configuration
scheduler:
  # Send periodic summary every N seconds
  summary_interval: 300
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved${NC}"
echo ""

# Summary
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Configuration Summary${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Telegram:${NC}"
echo "  Bot Token: ${BOT_TOKEN:0:10}...${BOT_TOKEN: -5}"
echo "  Allowed User: $USER_ID"
echo "  Chat ID: $CHAT_ID"
echo ""
echo -e "${GREEN}Alert Thresholds:${NC}"
echo "  CPU:  $CPU_WARN% (warning) / $CPU_CRIT% (critical)"
echo "  RAM:  $RAM_WARN% (warning) / $RAM_CRIT% (critical)"
echo "  Disk: $DISK_WARN% (warning) / $DISK_CRIT% (critical)"
echo ""
echo -e "${GREEN}Config saved to: $CONFIG_FILE${NC}"
echo ""

# Next steps
echo -e "${YELLOW}=== Next Steps ===${NC}"
echo ""

if [ "$IS_SYSTEM" = true ]; then
    echo "Start the monitoring service:"
    echo "  sudo systemctl start proxmox-monitor.service"
    echo "  sudo systemctl start proxmox-monitor.timer"
    echo ""
    echo "Check status:"
    echo "  sudo systemctl status proxmox-monitor.service"
    echo "  sudo journalctl -u proxmox-monitor.service -f"
else
    echo "Test the configuration locally:"
    echo "  cd $PROJECT_ROOT"
    echo "  python3 -m src.main"
    echo ""
    echo "Or install system-wide:"
    echo "  sudo bash scripts/install.sh"
fi

echo ""
echo -e "${GREEN}Setup complete! 🎉${NC}"
